
export const STATUS_SOLICITACAO = {
  ABERTA: 'ABERTA',
  ORCADA: 'ORÇADA',
  APROVADA: 'APROVADA',
  REJEITADA: 'REJEITADA',
  REDIRECIONADA: 'REDIRECIONADA',
  EM_MANUTENCAO: 'EM MANUTENÇÃO',
  ARRUMADA: 'ARRUMADA',
  PAGA: 'PAGA',
  FINALIZADA: 'FINALIZADA'
};

export const CORES_STATUS: { [key: string]: string } = {
  [STATUS_SOLICITACAO.ABERTA]: 'warning',
  [STATUS_SOLICITACAO.ORCADA]: 'info',
  [STATUS_SOLICITACAO.APROVADA]: 'success',
  [STATUS_SOLICITACAO.REJEITADA]: 'danger',
  [STATUS_SOLICITACAO.REDIRECIONADA]: 'purple',
  [STATUS_SOLICITACAO.EM_MANUTENCAO]: 'info',
  [STATUS_SOLICITACAO.ARRUMADA]: 'primary',
  [STATUS_SOLICITACAO.PAGA]: 'orange',
  [STATUS_SOLICITACAO.FINALIZADA]: 'success'
};