
export const STATUS_SOLICITACAO = {
  ABERTA: 'ABERTA',
  ORCADA: 'ORÇADA',
  APROVADA: 'APROVADA',
  REJEITADA: 'REJEITADA',
  REDIRECIONADA: 'REDIRECIONADA',
  EM_MANUTENCAO: 'EM MANUTENÇÃO',
  PAGA: 'PAGA',
  FINALIZADA: 'FINALIZADA'
};

export const CORES_STATUS: { [key: string]: string } = {
  [STATUS_SOLICITACAO.ABERTA]: 'warning',
  [STATUS_SOLICITACAO.ORCADA]: 'info',
  [STATUS_SOLICITACAO.APROVADA]: 'success',
  [STATUS_SOLICITACAO.REJEITADA]: 'danger',
  [STATUS_SOLICITACAO.PAGA]: 'primary'
};